name       : haskell-text-binary
version    : 0.2.1.1
release    : 4
source     :
    - http://hackage.haskell.org/package/text-binary-0.2.1.1/text-binary-0.2.1.1.tar.gz : b697b2bd09080643d4686705c779122129638904870df5c1d41c8fc72f08f4a1
license    : BSD-2-Clause
component  : programming.haskell
summary    : A compatibility layer providing Binary instances for strict and lazy text types for versions older than 1.2.1 of text.
description: |
    A compatibility layer providing Binary instances for strict and lazy text types for versions older than 1.2.1 of text.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
